theme: jekyll-theme-minimal
logo: /assets/img/logo-blue.png
title: TUBES System Ontology
description: https://w3id.org/tso
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true