theme: jekyll-theme-minimal
logo: /assets/img/logo-blue.png
title: TUBES System Ontology
description: The namespace for TSO terms is http://w3id.org/tso# and the suggested prefix is tso
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
